DROP TABLE IF EXISTS senior_centers;
CREATE TABLE senior_centers (id INTEGER PRIMARY KEY AUTOINCREMENT, sigun_nm TEXT, name TEXT, phone TEXT, address TEXT);
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('수원시', '태산1차(아)경로당', '031-297-4214', '경기도 수원시 권선구 고색동 886-83번지 태산1차아파트');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('수원시', '태산2차(아)경로당', '031-294-9059', '경기도 수원시 권선구 고색동 887-56번지 태산2차아파트');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('수원시', '대한(아)경로당', '031-291-6055', '경기도 수원시 권선구 고색동 368-1번지 대한아파트');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('수원시', '연합대원(아)경로당', '031-291-6838', '경기도 수원시 권선구 고색동 291번지 연합대원아파트');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('수원시', '온정마을경로당', '031-293-1375', '경기도 수원시 권선구 온정로30번길 53');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('성남시', '도촌8단지경로당', '031-758-2333', '경기도 성남시 중원구 도촌동 707번지 휴먼시아섬마을8단지아파트 임대');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('성남시', '도촌9단지경로당', '031-721-1018', '경기도 성남시 중원구 도촌동 708번지 휴먼시아섬마을9단지아파트 임대');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('성남시', '연꽃마을4단지경로당', '070-8193-3301', '경기도 성남시 중원구 여수동 601번지 연꽃마을아파트');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('성남시', '여수경로당', '031-721-2299', '경기도 성남시 중원구 여수울로15번길 18-3');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('성남시', '센트럴타운경로당', '031-755-9737', '경기도 성남시 중원구 여수동 600번지 센트럴타운3단지');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('의정부시', '호원한신2차아파트경로당', '031-876-6788', '경기도 의정부시 호원동 10-3번지 호원한신2차아파트');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('의정부시', '신일아파트경로당', '031-842-3713', '경기도 의정부시 신곡동 456번지 신일1차아파트 1층');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('의정부시', '서해아파트경로당', '031-842-5859', '경기도 의정부시 신곡동 353-43번지 서해아파트 1층');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('의정부시', '삼익한일아파트경로당', '031-876-2465', '경기도 의정부시 신곡동 723-1번지 삼익아파트 1층');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('의정부시', '신곡현대2차아파트경로당', '031-878-4116', '경기도 의정부시 신곡동 724-2번지 현대2차아파트 1층');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('안양시', '해당화경로당', '031-465-1237', '경기도 안양시 만안구 삼봉로19번길 13-6');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('안양시', '친목마을경로당', '', '경기도 안양시 만안구 오리로34번길 25-2');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('안양시', '비산제일경로당', '031-447-5505', '경기도 안양시 동안구 임곡로 74');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('안양시', '더포레스트힐(아)경로당', '031-346-8857', '경기도 안양시 동안구 임곡로 43');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('안양시', '비산삼성래미안(아)경로당', '031-447-4454', '경기도 안양시 동안구 비산동 425번지 삼성래미안아파트');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('부천시', '춘의주공경로당', '032-666-0858', '경기도 부천시 원미구 춘의동 237번지 대한주택공사아파트');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('부천시', '원종제3(남)경로당', '032-672-7920', '경기도 부천시 오정구 성지로85번길 65');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('부천시', '원종제3(여)경로당', '032-676-0127', '경기도 부천시 오정구 성지로85번길 65');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('부천시', '해주아파트경로당', '032-674-0505', '경기도 부천시 오정구 원종동 262-3번지 해주아파트');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('부천시', '동문5차아파트경로당(신동문경로당)', '032-679-6431', '경기도 부천시 오정구 원종동 121번지 동문굿모닝힐아파트');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('광명시', '신촌휴먼시아2단지경로당', '02-899-9128', '경기도 광명시 소하동 1366번지 신촌휴먼시아2단지아파트');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('광명시', '우림아파트경로당', '02-898-7766', '경기도 광명시 소하동 1272번지 우림필유아파트');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('광명시', '휴먼시아1단지경로당', '02-897-3616', '경기도 광명시 소하동 1284번지 휴먼시아1단지아파트');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('광명시', '휴먼시아3단지경로당', '02-897-5560', '경기도 광명시 소하동 1289번지 휴먼시아3단지아파트');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('광명시', '휴먼시아4단지경로당', '02-898-8686', '경기도 광명시 소하동 1292번지 휴먼시아4단지아파트');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('평택시', '소사SK뷰아파트', '031-618-1716', '경기도 평택시 소사동 524번지 평택소사에스케이뷰아파트');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('평택시', '시대코아아파트', '031-653-9984', '경기도 평택시 비전동 879-4번지 시대코아아파트');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('평택시', '시대한우리아파트', '031-657-2681', '경기도 평택시 비전동 874번지 시대한우리아파트');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('평택시', '송화주공아파트', '031-691-0200', '경기도 평택시 팽성읍 송화리 786-1번지 주공아파트');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('평택시', '송화홈타운아파트', '031-691-9549', '경기도 평택시 팽성읍 송화리 785-1번지 송화마을현대홈타운');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('동두천시', '조흥아파트 경로당', '031-867-0220', '경기도 동두천시 생연동 268-5번지 조흥아파트');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('동두천시', '에이스1단지 경로당', '031-864-0692', '경기도 동두천시 생연동 334-1번지 에이스아파트');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('동두천시', '에이스2단지 경로당', '031-868-2515', '경기도 동두천시 생연동 335번지 에이스2단지아파트');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('동두천시', '에이스3단지 경로당', '031-861-3588', '경기도 동두천시 생연동 350번지 에이스아파트');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('동두천시', '에이스4단지 경로당', '031-867-2264', '경기도 동두천시 생연동 354번지 에이스아파트');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('안산시', '구룡경로당', '031-829-1145', '경기도 안산시 상록구 구룡동길 4-4');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('안산시', '성호경로당', '031-879-7558', '경기도 안산시 상록구 성호로6길 14');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('안산시', '안골경로당', '031-825-3699', '경기도 안산시 상록구 웃말3길 12');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('안산시', '그린빌18단지경로당', '031-840-5625', '경기도 안산시 단원구 초지동 738번지 그린빌주공18단지아파트');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('안산시', '그린빌14단지경로당', '031-858-4747', '경기도 안산시 단원구 광덕2로 32');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('고양시', '능곡한라비발디경로당', '031-814-8190', '경기도 고양시 덕양구 토당동 298번지 한라비발디아파트');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('고양시', '능곡경로당', '031-973-1044', '경기도 고양시 덕양구 토당로104번길 18');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('고양시', '양우경로당', '031-817-1136', '경기도 고양시 덕양구 토당동 250번지 내안애양우아파트');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('고양시', '풍림아이원2단지경로당', '031-970-6474', '경기도 고양시 덕양구 토당동 60번지 풍림아이원아파트');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('고양시', '은빛마을5단지경로당', '031-964-5768', '경기도 고양시 덕양구 화정동 870번지 은빛마을5단지아파트');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('과천시', '10단지', '02-503-9880', '경기도 과천시 중앙동 67번지 주공아파트');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('과천시', '11단지', '', '경기도 과천시 관문로 151');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('과천시', '교 동', '02-507-0697', '경기도 과천시 희망2길 26');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('과천시', '중 앙', '', '경기도 과천시 향교말길 39');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('과천시', '푸르지오써밋', '02-504-1579', '경기도 과천시 중앙동 101번지 과천푸르지오써밋');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('구리시', '덕현경로당', '', '경기도 구리시 교문동 808번지 덕현아파트');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('구리시', '한가람경로당', '', '경기도 구리시 교문동 809번지 한가람아파트');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('구리시', '대명빌리지경로당', '', '경기도 구리시 이문안로 27');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('구리시', '왕숙제1경로당', '', '경기도 구리시 경춘로276번길 67-12');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('구리시', '원일경로당', '', '경기도 구리시 수택동 552-1번지 원일아파트');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('남양주시', '금곡1통 경로당', '031-591-3441', '경기도 남양주시 사릉로26번길 11');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('남양주시', '금곡2통  경로당', '031-591-4558', '경기도 남양주시 석실로650번길 22');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('남양주시', '금곡3통(어룡) 경로당', '031-511-1210', '경기도 남양주시 사릉로58번길 56');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('남양주시', '다산21통 부영4단지(구 부영4단지) 경로당', '031-556-9996', '경기도 남양주시 다산동 4002-1번지 플루리움4단지');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('남양주시', '다산22통(플루리움5단지) 경로당', '031-558-9760', '경기도 남양주시 다산동 4002-1번지 플루리움5단지');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('오산시', '동부삼환아파트 경로당', '', '경기도 오산시 원동 807번지 동부삼환아파트');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('오산시', '태영아파트 경로당', '', '경기도 오산시 원동 551번지 태영아파트');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('오산시', '우림아파트 경로당', '', '경기도 오산시 갈곶동 251번지 우림아파트');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('오산시', '운암5단지주공아파트 경로당', '', '경기도 오산시 원동 815-1번지 오산운암5단지주공아파트');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('오산시', '운암6단지주공아파트 경로당', '', '경기도 오산시 원동 815-4번지 오산운암6단지주공아파트');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('시흥시', '과림1통(무지내1통)', '031-313-8477', '경기도 시흥시 금오로121번길 12');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('시흥시', '과림4통(중림)', '02-2686-9934', '경기도 시흥시 금오로 476');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('시흥시', '과림동(3통)', '02-2681-5652', '경기도 시흥시 금오로327번길 20');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('시흥시', '무지내2통(과림2통)', '031-316-1715', '경기도 시흥시 금오로 229');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('시흥시', '거모16통', '031-492-4025', '경기도 시흥시 한우물로21번길 30');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('군포시', '당동삼성미도(아)경로당', '031-391-5741', '경기도 군포시 금당로 102');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('군포시', '당정대우(아)경로당', '031-427-2919', '경기도 군포시 당정역로 9');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('군포시', '당정성원(아)경로당', '031-451-3838', '경기도 군포시 당정동 997-1번지 청천마을성원아파트');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('군포시', '대원칸타빌(아)경로당', '031-427-0676', '경기도 군포시 당정역로64번길 9');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('군포시', '샘물경로당', '031-427-4588', '경기도 군포시 한세로66번길 4');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('의왕시', '오봉산마을1단지(아)경로당', '031-458-8794', '경기도 의왕시 고천동 544번지 오봉산마을1단지아파트');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('의왕시', '고천2통경로당', '031-452-9285', '경기도 의왕시 안골다리길 10');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('의왕시', '민들레베스파트경로당', '031-452-2559', '경기도 의왕시 오전동 388-1번지 민들레베스파트');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('의왕시', '솔거(아)경로당', '031-457-9324', '경기도 의왕시 왕곡동 600번지 솔거아파트');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('의왕시', '왕곡경로당', '031-452-4579', '경기도 의왕시 왕곡로 145');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('하남시', '취곡부녀경로당', '031-792-3301', '경기도 하남시 하남대로861번길 13');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('하남시', '자이@경로당', '031-792-5986', '경기도 하남시 덕풍동 691번지 하남자이');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('하남시', 'KCC@경로당', '031-792-0219', '경기도 하남시 덕풍동 690번지 케이씨씨아파트');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('하남시', '한솔솔파크@경로당', '031-795-6921', '경기도 하남시 하남대로887번길 25-1');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('하남시', '복지경로당', '031-793-4117', '경기도 하남시 수리북로27번길 19-13');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('용인시', '상미', '', '경기도 용인시 기흥구 상미로49번길 14');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('용인시', '기흥더샵프라임뷰', '', '경기도 용인시 기흥구 구갈로 71-18');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('용인시', '신갈11통', '', '경기도 용인시 기흥구 신갈동 45-15번지 흥덕다세대주택');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('용인시', '신갈12통', '', '경기도 용인시 기흥구 신갈동 2-1번지 동오연립');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('용인시', '드림랜드(아)', '', '경기도 용인시 기흥구 신갈동 116-2번지 드림랜드아파트');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('파주시', '위전2리 경로당', '031-945-0549', '경기도 파주시 월롱면 은행나무길 80');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('파주시', '위전3리 경로당', '031-945-7010', '경기도 파주시 월롱면 누현2길 89');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('파주시', '위전4리 경로당', '031-945-8610', '경기도 파주시 월롱면 도감로194번길 10');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('파주시', '가월리 경로당', '031-959-3586', '경기도 파주시 적성면 달빛길 81');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('파주시', '가월리 할머니 경로당', '031-959-1230', '경기도 파주시 적성면 달빛길 81');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('이천시', '아미3리(현대3차A) 경로당', '031-634-2490', '경기도 이천시 부발읍 아미리 699-7번지 이천현대3차아파트');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('이천시', '아미4리(현대7차A) 경로당', '031-635-7424', '경기도 이천시 부발읍 아미리 753번지 아미리7차현대아파트');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('이천시', '아미6리(현대성우오스타 2단지 A) 경로당', '031-631-6489', '경기도 이천시 부발읍 아미리 1245번지 현대성우오스타2단지');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('이천시', '아미7리(현대성우오스타3-4단지 A) 경로당', '031-635-9564', '경기도 이천시 부발읍 아미리 1247번지 현대성우오스타4단지');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('이천시', '아미8리(신일해피트리빌) 경로당', '', '경기도 이천시 부발읍 아미리 729번지 이천신일해피트리트리빌2단지');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('안성시', '대근', '', '경기도 안성시 죽산면 대근길 16');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('안성시', '송학', '', '경기도 안성시 일죽면 동부길 18');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('안성시', '능동', '', '경기도 안성시 일죽면 능국길 66');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('안성시', '운전', '', '경기도 안성시 일죽면 일죽당촌길 2-16');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('안성시', '국동', '', '경기도 안성시 일죽면 국동길 142-9');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('김포시', '신곡11리', '', '경기도 김포시 고촌읍 장차로 38-3');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('김포시', '신곡12리', '', '경기도 김포시 고촌읍 은행영사정로23번길 52-15');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('김포시', '신곡4리', '031-985-4300', '경기도 김포시 고촌읍 장차로31번길 37');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('김포시', '전호1리', '', '경기도 김포시 고촌읍 전호로26번길 4');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('김포시', '신곡3,8,14리', '', '경기도 김포시 고촌읍 인향로24번길 22-19');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('화성시', '장안1,2리할머니  경로당', '031-358-1349', '경기도 화성시 장안면 상두원길 79');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('화성시', '장안1,2리할아버지  경로당', '031-358-5211', '경기도 화성시 장안면 상두원길 79');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('화성시', '장안3리  경로당', '031-358-5742', '경기도 화성시 장안면 동편길 38');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('화성시', '장안4리  경로당', '', '경기도 화성시 장안면 장안고잔길 88');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('화성시', '장안5리  경로당', '031-358-0206', '경기도 화성시 장안면 온수골1길 100-2');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('광주시', '쌍용더플래티넘광주아파트경로당', '', '경기도 광주시 초월읍 대쌍령리 496번지 쌍용더플래티넘광주');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('광주시', '초월역한라비발디아파트', '', '경기도 광주시 초월읍 쌍동리 400번지 광주초월역한라비발디');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('광주시', '곤지암1리', '031-762-6455', '경기도 광주시 곤지암읍 곤지암로11번길 29');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('광주시', '곤지암2리', '031-769-3126', '경기도 광주시 곤지암읍 경충대로543번길 62');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('광주시', '곤지암3리', '', '경기도 광주시 곤지암읍 대석동길45번길 14');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('양주시', '운암1리', '031-862-7303', '경기도 양주시 은현면 화합로691번길 172');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('양주시', '효촌2리', '031-876-9094', '경기도 양주시 광적면 화합로81번길 116');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('양주시', '우고리(효가동)', '031-836-0101', '경기도 양주시 광적면 부흥로618번길 90-64');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('양주시', '덕도2리', '031-871-8788', '경기도 양주시 광적면 화합로 220');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('양주시', '가납2리', '031-836-3168', '경기도 양주시 광적면 그루고개로194번길 24');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('포천시', '장암2리경로당', '031-532-4910', '경기도 포천시 이동면 성장로 1199-9');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('포천시', '장암4리경로당', '031-532-4803', '경기도 포천시 이동면 장암2길 14-1');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('포천시', '장암5리경로당', '031-532-6146', '경기도 포천시 이동면 장암4길 16');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('포천시', '장암6리경로당', '031-533-8879', '경기도 포천시 이동면 늠바위길 99');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('포천시', '대회산리경로당', '031-536-5066', '경기도 포천시 영북면 대회산길 67');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('여주시', '금강', '031-883-3057', '경기도 여주시 가남읍 태평1길 26');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('여주시', '금곡리', '031-882-2468', '경기도 여주시 가남읍 금곡길 64');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('여주시', '금당1리', '031-882-5406', '경기도 여주시 가남읍 김대2길 2-21');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('여주시', '금당2리', '031-882-5693', '경기도 여주시 가남읍 금당4길 14');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('여주시', '김대', '031-882-5444', '경기도 여주시 가남읍 김대2길 2-22');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('연천군', '통현1리', '031-834-1237', '경기도 연천군 연천읍 평화로 1236');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('연천군', '와초리', '031-834-2018', '경기도 연천군 연천읍 와초길 53');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('연천군', '상1리(남)', '031-834-0392', '경기도 연천군 연천읍 신망로 27-1');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('연천군', '상1리(여)', '', '경기도 연천군 연천읍 신망로12번길 37');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('연천군', '상2리', '031-834-9331', '경기도 연천군 연천읍 연신로466번길 4');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('가평군', '대보1리(다부산) 경로당', '031-584-1066', '경기도 가평군 조종면 대보간선로 337');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('가평군', '대보2리 경로당', '031-585-3428', '경기도 가평군 조종면 대보간선로611번길 5');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('가평군', '우목골경로당', '', '경기도 가평군 조종면 명지산로 152');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('가평군', '북면분회', '031-582-5486', '경기도 가평군 북면 화악산로11번길 6-8');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('가평군', '목동1리 경로당', '031-582-8444', '경기도 가평군 북면 화악산로 8-12');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('양평군', '대흥1리', '031-772-1985', '경기도 양평군 양평읍 황골길 14');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('양평군', '대흥2리', '031-772-1306', '경기도 양평군 양평읍 천변길 60');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('양평군', '대흥3리', '031-772-1336', '경기도 양평군 양평읍 미리내길18번길 34');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('양평군', '봉성1리', '031-772-1360', '경기도 양평군 양평읍 봉성길73번길 4');
INSERT INTO senior_centers (sigun_nm, name, phone, address) VALUES ('양평군', '봉성2리', '031-774-0311', '경기도 양평군 양평읍 원덕흑천길 6');
